//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DatabaseModel", "FK__Receipt__CCID__2C3393D0", "CostCenter", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VitsWCF.CostCenter), "Receipt", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VitsWCF.Receipt), true)]
[assembly: EdmRelationshipAttribute("DatabaseModel", "FK__Office__CID__08EA5793", "Country", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VitsWCF.Country), "Office", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VitsWCF.Office), true)]
[assembly: EdmRelationshipAttribute("DatabaseModel", "FK__Trip__CID__1A14E395", "Country", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VitsWCF.Country), "Trip", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VitsWCF.Trip), true)]
[assembly: EdmRelationshipAttribute("DatabaseModel", "FK__Mission__Manager__0EA330E9", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VitsWCF.Employee), "Mission", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VitsWCF.Mission), true)]
[assembly: EdmRelationshipAttribute("DatabaseModel", "FK__Report__EID__1ED998B2", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VitsWCF.Employee), "Report", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VitsWCF.Report), true)]
[assembly: EdmRelationshipAttribute("DatabaseModel", "FK__TravelAdvan__EID__15502E78", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VitsWCF.Employee), "TravelAdvances", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VitsWCF.TravelAdvances), true)]
[assembly: EdmRelationshipAttribute("DatabaseModel", "FK__Trip__EID__182C9B23", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VitsWCF.Employee), "Trip", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VitsWCF.Trip), true)]
[assembly: EdmRelationshipAttribute("DatabaseModel", "FK__Mission__OID__0DAF0CB0", "Office", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VitsWCF.Office), "Mission", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VitsWCF.Mission), true)]
[assembly: EdmRelationshipAttribute("DatabaseModel", "FK__Report__MID__1FCDBCEB", "Mission", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VitsWCF.Mission), "Report", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VitsWCF.Report), true)]
[assembly: EdmRelationshipAttribute("DatabaseModel", "FK__TravelAdvan__MID__164452B1", "Mission", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VitsWCF.Mission), "TravelAdvances", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VitsWCF.TravelAdvances), true)]
[assembly: EdmRelationshipAttribute("DatabaseModel", "FK__Trip__MID__1920BF5C", "Mission", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VitsWCF.Mission), "Trip", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VitsWCF.Trip), true)]
[assembly: EdmRelationshipAttribute("DatabaseModel", "FK__Receipt__REPID__2B3F6F97", "Report", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VitsWCF.Report), "Receipt", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VitsWCF.Receipt), true)]
[assembly: EdmRelationshipAttribute("DatabaseModel", "EmployeeMission", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VitsWCF.Employee), "Mission", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VitsWCF.Mission))]

#endregion

namespace VitsWCF
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DatabaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DatabaseEntities object using the connection string found in the 'DatabaseEntities' section of the application configuration file.
        /// </summary>
        public DatabaseEntities() : base("name=DatabaseEntities", "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatabaseEntities object.
        /// </summary>
        public DatabaseEntities(string connectionString) : base(connectionString, "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatabaseEntities object.
        /// </summary>
        public DatabaseEntities(EntityConnection connection) : base(connection, "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CostCenter> CostCenter
        {
            get
            {
                if ((_CostCenter == null))
                {
                    _CostCenter = base.CreateObjectSet<CostCenter>("CostCenter");
                }
                return _CostCenter;
            }
        }
        private ObjectSet<CostCenter> _CostCenter;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Country> Country
        {
            get
            {
                if ((_Country == null))
                {
                    _Country = base.CreateObjectSet<Country>("Country");
                }
                return _Country;
            }
        }
        private ObjectSet<Country> _Country;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employee> Employee
        {
            get
            {
                if ((_Employee == null))
                {
                    _Employee = base.CreateObjectSet<Employee>("Employee");
                }
                return _Employee;
            }
        }
        private ObjectSet<Employee> _Employee;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Mission> Mission
        {
            get
            {
                if ((_Mission == null))
                {
                    _Mission = base.CreateObjectSet<Mission>("Mission");
                }
                return _Mission;
            }
        }
        private ObjectSet<Mission> _Mission;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Office> Office
        {
            get
            {
                if ((_Office == null))
                {
                    _Office = base.CreateObjectSet<Office>("Office");
                }
                return _Office;
            }
        }
        private ObjectSet<Office> _Office;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Receipt> Receipt
        {
            get
            {
                if ((_Receipt == null))
                {
                    _Receipt = base.CreateObjectSet<Receipt>("Receipt");
                }
                return _Receipt;
            }
        }
        private ObjectSet<Receipt> _Receipt;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Report> Report
        {
            get
            {
                if ((_Report == null))
                {
                    _Report = base.CreateObjectSet<Report>("Report");
                }
                return _Report;
            }
        }
        private ObjectSet<Report> _Report;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TravelAdvances> TravelAdvances
        {
            get
            {
                if ((_TravelAdvances == null))
                {
                    _TravelAdvances = base.CreateObjectSet<TravelAdvances>("TravelAdvances");
                }
                return _TravelAdvances;
            }
        }
        private ObjectSet<TravelAdvances> _TravelAdvances;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Trip> Trip
        {
            get
            {
                if ((_Trip == null))
                {
                    _Trip = base.CreateObjectSet<Trip>("Trip");
                }
                return _Trip;
            }
        }
        private ObjectSet<Trip> _Trip;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CostCenter EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCostCenter(CostCenter costCenter)
        {
            base.AddObject("CostCenter", costCenter);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Country EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCountry(Country country)
        {
            base.AddObject("Country", country);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employee EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployee(Employee employee)
        {
            base.AddObject("Employee", employee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Mission EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMission(Mission mission)
        {
            base.AddObject("Mission", mission);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Office EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOffice(Office office)
        {
            base.AddObject("Office", office);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Receipt EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReceipt(Receipt receipt)
        {
            base.AddObject("Receipt", receipt);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Report EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReport(Report report)
        {
            base.AddObject("Report", report);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TravelAdvances EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTravelAdvances(TravelAdvances travelAdvances)
        {
            base.AddObject("TravelAdvances", travelAdvances);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Trip EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTrip(Trip trip)
        {
            base.AddObject("Trip", trip);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="CostCenter")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CostCenter : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CostCenter object.
        /// </summary>
        /// <param name="cCID">Initial value of the CCID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static CostCenter CreateCostCenter(global::System.Byte cCID, global::System.String name)
        {
            CostCenter costCenter = new CostCenter();
            costCenter.CCID = cCID;
            costCenter.Name = name;
            return costCenter;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte CCID
        {
            get
            {
                return _CCID;
            }
            set
            {
                if (_CCID != value)
                {
                    OnCCIDChanging(value);
                    ReportPropertyChanging("CCID");
                    _CCID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CCID");
                    OnCCIDChanged();
                }
            }
        }
        private global::System.Byte _CCID;
        partial void OnCCIDChanging(global::System.Byte value);
        partial void OnCCIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK__Receipt__CCID__2C3393D0", "Receipt")]
        public EntityCollection<Receipt> Receipt
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Receipt>("DatabaseModel.FK__Receipt__CCID__2C3393D0", "Receipt");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Receipt>("DatabaseModel.FK__Receipt__CCID__2C3393D0", "Receipt", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Country")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Country : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Country object.
        /// </summary>
        /// <param name="cID">Initial value of the CID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Country CreateCountry(global::System.Byte cID, global::System.String name)
        {
            Country country = new Country();
            country.CID = cID;
            country.Name = name;
            return country;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte CID
        {
            get
            {
                return _CID;
            }
            set
            {
                if (_CID != value)
                {
                    OnCIDChanging(value);
                    ReportPropertyChanging("CID");
                    _CID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CID");
                    OnCIDChanged();
                }
            }
        }
        private global::System.Byte _CID;
        partial void OnCIDChanging(global::System.Byte value);
        partial void OnCIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK__Office__CID__08EA5793", "Office")]
        public EntityCollection<Office> Office
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Office>("DatabaseModel.FK__Office__CID__08EA5793", "Office");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Office>("DatabaseModel.FK__Office__CID__08EA5793", "Office", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK__Trip__CID__1A14E395", "Trip")]
        public EntityCollection<Trip> Trip
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Trip>("DatabaseModel.FK__Trip__CID__1A14E395", "Trip");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Trip>("DatabaseModel.FK__Trip__CID__1A14E395", "Trip", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="eID">Initial value of the EID property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="adress">Initial value of the Adress property.</param>
        /// <param name="zipCode">Initial value of the ZipCode property.</param>
        /// <param name="city">Initial value of the City property.</param>
        /// <param name="idNumber">Initial value of the IdNumber property.</param>
        /// <param name="manager">Initial value of the Manager property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        public static Employee CreateEmployee(global::System.Byte eID, global::System.String firstName, global::System.String lastName, global::System.String adress, global::System.String zipCode, global::System.String city, global::System.String idNumber, global::System.Boolean manager, global::System.String email)
        {
            Employee employee = new Employee();
            employee.EID = eID;
            employee.FirstName = firstName;
            employee.LastName = lastName;
            employee.Adress = adress;
            employee.ZipCode = zipCode;
            employee.City = city;
            employee.IdNumber = idNumber;
            employee.Manager = manager;
            employee.Email = email;
            return employee;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte EID
        {
            get
            {
                return _EID;
            }
            set
            {
                if (_EID != value)
                {
                    OnEIDChanging(value);
                    ReportPropertyChanging("EID");
                    _EID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EID");
                    OnEIDChanged();
                }
            }
        }
        private global::System.Byte _EID;
        partial void OnEIDChanging(global::System.Byte value);
        partial void OnEIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Adress
        {
            get
            {
                return _Adress;
            }
            set
            {
                OnAdressChanging(value);
                ReportPropertyChanging("Adress");
                _Adress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Adress");
                OnAdressChanged();
            }
        }
        private global::System.String _Adress;
        partial void OnAdressChanging(global::System.String value);
        partial void OnAdressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ZipCode
        {
            get
            {
                return _ZipCode;
            }
            set
            {
                OnZipCodeChanging(value);
                ReportPropertyChanging("ZipCode");
                _ZipCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ZipCode");
                OnZipCodeChanged();
            }
        }
        private global::System.String _ZipCode;
        partial void OnZipCodeChanging(global::System.String value);
        partial void OnZipCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IdNumber
        {
            get
            {
                return _IdNumber;
            }
            set
            {
                OnIdNumberChanging(value);
                ReportPropertyChanging("IdNumber");
                _IdNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IdNumber");
                OnIdNumberChanged();
            }
        }
        private global::System.String _IdNumber;
        partial void OnIdNumberChanging(global::System.String value);
        partial void OnIdNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Manager
        {
            get
            {
                return _Manager;
            }
            set
            {
                OnManagerChanging(value);
                ReportPropertyChanging("Manager");
                _Manager = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Manager");
                OnManagerChanged();
            }
        }
        private global::System.Boolean _Manager;
        partial void OnManagerChanging(global::System.Boolean value);
        partial void OnManagerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK__Mission__Manager__0EA330E9", "Mission")]
        public EntityCollection<Mission> Mission
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Mission>("DatabaseModel.FK__Mission__Manager__0EA330E9", "Mission");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Mission>("DatabaseModel.FK__Mission__Manager__0EA330E9", "Mission", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK__Report__EID__1ED998B2", "Report")]
        public EntityCollection<Report> Report
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Report>("DatabaseModel.FK__Report__EID__1ED998B2", "Report");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Report>("DatabaseModel.FK__Report__EID__1ED998B2", "Report", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK__TravelAdvan__EID__15502E78", "TravelAdvances")]
        public EntityCollection<TravelAdvances> TravelAdvances
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TravelAdvances>("DatabaseModel.FK__TravelAdvan__EID__15502E78", "TravelAdvances");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TravelAdvances>("DatabaseModel.FK__TravelAdvan__EID__15502E78", "TravelAdvances", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK__Trip__EID__182C9B23", "Trip")]
        public EntityCollection<Trip> Trip
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Trip>("DatabaseModel.FK__Trip__EID__182C9B23", "Trip");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Trip>("DatabaseModel.FK__Trip__EID__182C9B23", "Trip", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "EmployeeMission", "Mission")]
        public EntityCollection<Mission> Mission1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Mission>("DatabaseModel.EmployeeMission", "Mission");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Mission>("DatabaseModel.EmployeeMission", "Mission", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Mission")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Mission : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Mission object.
        /// </summary>
        /// <param name="mID">Initial value of the MID property.</param>
        /// <param name="oID">Initial value of the OID property.</param>
        /// <param name="manager">Initial value of the Manager property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static Mission CreateMission(global::System.Byte mID, global::System.Byte oID, global::System.Byte manager, global::System.String description)
        {
            Mission mission = new Mission();
            mission.MID = mID;
            mission.OID = oID;
            mission.Manager = manager;
            mission.Description = description;
            return mission;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte MID
        {
            get
            {
                return _MID;
            }
            set
            {
                if (_MID != value)
                {
                    OnMIDChanging(value);
                    ReportPropertyChanging("MID");
                    _MID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MID");
                    OnMIDChanged();
                }
            }
        }
        private global::System.Byte _MID;
        partial void OnMIDChanging(global::System.Byte value);
        partial void OnMIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte OID
        {
            get
            {
                return _OID;
            }
            set
            {
                OnOIDChanging(value);
                ReportPropertyChanging("OID");
                _OID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OID");
                OnOIDChanged();
            }
        }
        private global::System.Byte _OID;
        partial void OnOIDChanging(global::System.Byte value);
        partial void OnOIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Manager
        {
            get
            {
                return _Manager;
            }
            set
            {
                OnManagerChanging(value);
                ReportPropertyChanging("Manager");
                _Manager = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Manager");
                OnManagerChanged();
            }
        }
        private global::System.Byte _Manager;
        partial void OnManagerChanging(global::System.Byte value);
        partial void OnManagerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartDate;
        partial void OnStartDateChanging(Nullable<global::System.DateTime> value);
        partial void OnStartDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK__Mission__Manager__0EA330E9", "Employee")]
        public Employee Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DatabaseModel.FK__Mission__Manager__0EA330E9", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DatabaseModel.FK__Mission__Manager__0EA330E9", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DatabaseModel.FK__Mission__Manager__0EA330E9", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("DatabaseModel.FK__Mission__Manager__0EA330E9", "Employee", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK__Mission__OID__0DAF0CB0", "Office")]
        public Office Office
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Office>("DatabaseModel.FK__Mission__OID__0DAF0CB0", "Office").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Office>("DatabaseModel.FK__Mission__OID__0DAF0CB0", "Office").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Office> OfficeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Office>("DatabaseModel.FK__Mission__OID__0DAF0CB0", "Office");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Office>("DatabaseModel.FK__Mission__OID__0DAF0CB0", "Office", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK__Report__MID__1FCDBCEB", "Report")]
        public EntityCollection<Report> Report
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Report>("DatabaseModel.FK__Report__MID__1FCDBCEB", "Report");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Report>("DatabaseModel.FK__Report__MID__1FCDBCEB", "Report", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK__TravelAdvan__MID__164452B1", "TravelAdvances")]
        public EntityCollection<TravelAdvances> TravelAdvances
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TravelAdvances>("DatabaseModel.FK__TravelAdvan__MID__164452B1", "TravelAdvances");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TravelAdvances>("DatabaseModel.FK__TravelAdvan__MID__164452B1", "TravelAdvances", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK__Trip__MID__1920BF5C", "Trip")]
        public EntityCollection<Trip> Trip
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Trip>("DatabaseModel.FK__Trip__MID__1920BF5C", "Trip");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Trip>("DatabaseModel.FK__Trip__MID__1920BF5C", "Trip", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "EmployeeMission", "Employee")]
        public EntityCollection<Employee> Employee1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Employee>("DatabaseModel.EmployeeMission", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Employee>("DatabaseModel.EmployeeMission", "Employee", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Office")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Office : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Office object.
        /// </summary>
        /// <param name="oID">Initial value of the OID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="orgNumber">Initial value of the OrgNumber property.</param>
        /// <param name="adress">Initial value of the Adress property.</param>
        /// <param name="zipCode">Initial value of the ZipCode property.</param>
        /// <param name="city">Initial value of the City property.</param>
        /// <param name="cID">Initial value of the CID property.</param>
        public static Office CreateOffice(global::System.Byte oID, global::System.String name, global::System.Int32 orgNumber, global::System.String adress, global::System.Int32 zipCode, global::System.String city, global::System.Byte cID)
        {
            Office office = new Office();
            office.OID = oID;
            office.Name = name;
            office.OrgNumber = orgNumber;
            office.Adress = adress;
            office.ZipCode = zipCode;
            office.City = city;
            office.CID = cID;
            return office;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte OID
        {
            get
            {
                return _OID;
            }
            set
            {
                if (_OID != value)
                {
                    OnOIDChanging(value);
                    ReportPropertyChanging("OID");
                    _OID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OID");
                    OnOIDChanged();
                }
            }
        }
        private global::System.Byte _OID;
        partial void OnOIDChanging(global::System.Byte value);
        partial void OnOIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrgNumber
        {
            get
            {
                return _OrgNumber;
            }
            set
            {
                OnOrgNumberChanging(value);
                ReportPropertyChanging("OrgNumber");
                _OrgNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrgNumber");
                OnOrgNumberChanged();
            }
        }
        private global::System.Int32 _OrgNumber;
        partial void OnOrgNumberChanging(global::System.Int32 value);
        partial void OnOrgNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Adress
        {
            get
            {
                return _Adress;
            }
            set
            {
                OnAdressChanging(value);
                ReportPropertyChanging("Adress");
                _Adress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Adress");
                OnAdressChanged();
            }
        }
        private global::System.String _Adress;
        partial void OnAdressChanging(global::System.String value);
        partial void OnAdressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ZipCode
        {
            get
            {
                return _ZipCode;
            }
            set
            {
                OnZipCodeChanging(value);
                ReportPropertyChanging("ZipCode");
                _ZipCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ZipCode");
                OnZipCodeChanged();
            }
        }
        private global::System.Int32 _ZipCode;
        partial void OnZipCodeChanging(global::System.Int32 value);
        partial void OnZipCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte CID
        {
            get
            {
                return _CID;
            }
            set
            {
                OnCIDChanging(value);
                ReportPropertyChanging("CID");
                _CID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CID");
                OnCIDChanged();
            }
        }
        private global::System.Byte _CID;
        partial void OnCIDChanging(global::System.Byte value);
        partial void OnCIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK__Office__CID__08EA5793", "Country")]
        public Country Country
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Country>("DatabaseModel.FK__Office__CID__08EA5793", "Country").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Country>("DatabaseModel.FK__Office__CID__08EA5793", "Country").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Country> CountryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Country>("DatabaseModel.FK__Office__CID__08EA5793", "Country");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Country>("DatabaseModel.FK__Office__CID__08EA5793", "Country", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK__Mission__OID__0DAF0CB0", "Mission")]
        public EntityCollection<Mission> Mission
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Mission>("DatabaseModel.FK__Mission__OID__0DAF0CB0", "Mission");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Mission>("DatabaseModel.FK__Mission__OID__0DAF0CB0", "Mission", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Receipt")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Receipt : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Receipt object.
        /// </summary>
        /// <param name="rECID">Initial value of the RECID property.</param>
        /// <param name="rEPID">Initial value of the REPID property.</param>
        /// <param name="cCID">Initial value of the CCID property.</param>
        /// <param name="sum">Initial value of the Sum property.</param>
        /// <param name="vAT">Initial value of the VAT property.</param>
        /// <param name="from">Initial value of the From property.</param>
        /// <param name="to">Initial value of the To property.</param>
        public static Receipt CreateReceipt(global::System.Byte rECID, global::System.Byte rEPID, global::System.Byte cCID, global::System.Int32 sum, global::System.Int32 vAT, global::System.DateTime from, global::System.DateTime to)
        {
            Receipt receipt = new Receipt();
            receipt.RECID = rECID;
            receipt.REPID = rEPID;
            receipt.CCID = cCID;
            receipt.Sum = sum;
            receipt.VAT = vAT;
            receipt.From = from;
            receipt.To = to;
            return receipt;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte RECID
        {
            get
            {
                return _RECID;
            }
            set
            {
                if (_RECID != value)
                {
                    OnRECIDChanging(value);
                    ReportPropertyChanging("RECID");
                    _RECID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RECID");
                    OnRECIDChanged();
                }
            }
        }
        private global::System.Byte _RECID;
        partial void OnRECIDChanging(global::System.Byte value);
        partial void OnRECIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte REPID
        {
            get
            {
                return _REPID;
            }
            set
            {
                OnREPIDChanging(value);
                ReportPropertyChanging("REPID");
                _REPID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("REPID");
                OnREPIDChanged();
            }
        }
        private global::System.Byte _REPID;
        partial void OnREPIDChanging(global::System.Byte value);
        partial void OnREPIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte CCID
        {
            get
            {
                return _CCID;
            }
            set
            {
                OnCCIDChanging(value);
                ReportPropertyChanging("CCID");
                _CCID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CCID");
                OnCCIDChanged();
            }
        }
        private global::System.Byte _CCID;
        partial void OnCCIDChanging(global::System.Byte value);
        partial void OnCCIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Sum
        {
            get
            {
                return _Sum;
            }
            set
            {
                OnSumChanging(value);
                ReportPropertyChanging("Sum");
                _Sum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sum");
                OnSumChanged();
            }
        }
        private global::System.Int32 _Sum;
        partial void OnSumChanging(global::System.Int32 value);
        partial void OnSumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VAT
        {
            get
            {
                return _VAT;
            }
            set
            {
                OnVATChanging(value);
                ReportPropertyChanging("VAT");
                _VAT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VAT");
                OnVATChanged();
            }
        }
        private global::System.Int32 _VAT;
        partial void OnVATChanging(global::System.Int32 value);
        partial void OnVATChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime From
        {
            get
            {
                return _From;
            }
            set
            {
                OnFromChanging(value);
                ReportPropertyChanging("From");
                _From = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("From");
                OnFromChanged();
            }
        }
        private global::System.DateTime _From;
        partial void OnFromChanging(global::System.DateTime value);
        partial void OnFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime To
        {
            get
            {
                return _To;
            }
            set
            {
                OnToChanging(value);
                ReportPropertyChanging("To");
                _To = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("To");
                OnToChanged();
            }
        }
        private global::System.DateTime _To;
        partial void OnToChanging(global::System.DateTime value);
        partial void OnToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK__Receipt__CCID__2C3393D0", "CostCenter")]
        public CostCenter CostCenter
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CostCenter>("DatabaseModel.FK__Receipt__CCID__2C3393D0", "CostCenter").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CostCenter>("DatabaseModel.FK__Receipt__CCID__2C3393D0", "CostCenter").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CostCenter> CostCenterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CostCenter>("DatabaseModel.FK__Receipt__CCID__2C3393D0", "CostCenter");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CostCenter>("DatabaseModel.FK__Receipt__CCID__2C3393D0", "CostCenter", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK__Receipt__REPID__2B3F6F97", "Report")]
        public Report Report
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Report>("DatabaseModel.FK__Receipt__REPID__2B3F6F97", "Report").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Report>("DatabaseModel.FK__Receipt__REPID__2B3F6F97", "Report").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Report> ReportReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Report>("DatabaseModel.FK__Receipt__REPID__2B3F6F97", "Report");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Report>("DatabaseModel.FK__Receipt__REPID__2B3F6F97", "Report", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Report")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Report : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Report object.
        /// </summary>
        /// <param name="rEPID">Initial value of the REPID property.</param>
        /// <param name="eID">Initial value of the EID property.</param>
        /// <param name="mID">Initial value of the MID property.</param>
        /// <param name="expenses">Initial value of the Expenses property.</param>
        /// <param name="car">Initial value of the Car property.</param>
        public static Report CreateReport(global::System.Byte rEPID, global::System.Byte eID, global::System.Byte mID, global::System.Int32 expenses, global::System.Boolean car)
        {
            Report report = new Report();
            report.REPID = rEPID;
            report.EID = eID;
            report.MID = mID;
            report.Expenses = expenses;
            report.Car = car;
            return report;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte REPID
        {
            get
            {
                return _REPID;
            }
            set
            {
                if (_REPID != value)
                {
                    OnREPIDChanging(value);
                    ReportPropertyChanging("REPID");
                    _REPID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("REPID");
                    OnREPIDChanged();
                }
            }
        }
        private global::System.Byte _REPID;
        partial void OnREPIDChanging(global::System.Byte value);
        partial void OnREPIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte EID
        {
            get
            {
                return _EID;
            }
            set
            {
                OnEIDChanging(value);
                ReportPropertyChanging("EID");
                _EID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EID");
                OnEIDChanged();
            }
        }
        private global::System.Byte _EID;
        partial void OnEIDChanging(global::System.Byte value);
        partial void OnEIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte MID
        {
            get
            {
                return _MID;
            }
            set
            {
                OnMIDChanging(value);
                ReportPropertyChanging("MID");
                _MID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MID");
                OnMIDChanged();
            }
        }
        private global::System.Byte _MID;
        partial void OnMIDChanging(global::System.Byte value);
        partial void OnMIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Expenses
        {
            get
            {
                return _Expenses;
            }
            set
            {
                OnExpensesChanging(value);
                ReportPropertyChanging("Expenses");
                _Expenses = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Expenses");
                OnExpensesChanged();
            }
        }
        private global::System.Int32 _Expenses;
        partial void OnExpensesChanging(global::System.Int32 value);
        partial void OnExpensesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Car
        {
            get
            {
                return _Car;
            }
            set
            {
                OnCarChanging(value);
                ReportPropertyChanging("Car");
                _Car = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Car");
                OnCarChanged();
            }
        }
        private global::System.Boolean _Car;
        partial void OnCarChanging(global::System.Boolean value);
        partial void OnCarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Miles
        {
            get
            {
                return _Miles;
            }
            set
            {
                OnMilesChanging(value);
                ReportPropertyChanging("Miles");
                _Miles = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Miles");
                OnMilesChanged();
            }
        }
        private Nullable<global::System.Int32> _Miles;
        partial void OnMilesChanging(Nullable<global::System.Int32> value);
        partial void OnMilesChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK__Report__EID__1ED998B2", "Employee")]
        public Employee Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DatabaseModel.FK__Report__EID__1ED998B2", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DatabaseModel.FK__Report__EID__1ED998B2", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DatabaseModel.FK__Report__EID__1ED998B2", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("DatabaseModel.FK__Report__EID__1ED998B2", "Employee", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK__Report__MID__1FCDBCEB", "Mission")]
        public Mission Mission
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mission>("DatabaseModel.FK__Report__MID__1FCDBCEB", "Mission").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mission>("DatabaseModel.FK__Report__MID__1FCDBCEB", "Mission").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Mission> MissionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mission>("DatabaseModel.FK__Report__MID__1FCDBCEB", "Mission");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Mission>("DatabaseModel.FK__Report__MID__1FCDBCEB", "Mission", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK__Receipt__REPID__2B3F6F97", "Receipt")]
        public EntityCollection<Receipt> Receipt
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Receipt>("DatabaseModel.FK__Receipt__REPID__2B3F6F97", "Receipt");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Receipt>("DatabaseModel.FK__Receipt__REPID__2B3F6F97", "Receipt", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="TravelAdvances")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TravelAdvances : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TravelAdvances object.
        /// </summary>
        /// <param name="tID">Initial value of the TID property.</param>
        /// <param name="total">Initial value of the Total property.</param>
        /// <param name="approved">Initial value of the Approved property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="eID">Initial value of the EID property.</param>
        /// <param name="mID">Initial value of the MID property.</param>
        public static TravelAdvances CreateTravelAdvances(global::System.Byte tID, global::System.Int32 total, global::System.Boolean approved, global::System.DateTime date, global::System.Byte eID, global::System.Byte mID)
        {
            TravelAdvances travelAdvances = new TravelAdvances();
            travelAdvances.TID = tID;
            travelAdvances.Total = total;
            travelAdvances.Approved = approved;
            travelAdvances.Date = date;
            travelAdvances.EID = eID;
            travelAdvances.MID = mID;
            return travelAdvances;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte TID
        {
            get
            {
                return _TID;
            }
            set
            {
                if (_TID != value)
                {
                    OnTIDChanging(value);
                    ReportPropertyChanging("TID");
                    _TID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TID");
                    OnTIDChanged();
                }
            }
        }
        private global::System.Byte _TID;
        partial void OnTIDChanging(global::System.Byte value);
        partial void OnTIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private global::System.Int32 _Total;
        partial void OnTotalChanging(global::System.Int32 value);
        partial void OnTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Approved
        {
            get
            {
                return _Approved;
            }
            set
            {
                OnApprovedChanging(value);
                ReportPropertyChanging("Approved");
                _Approved = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Approved");
                OnApprovedChanged();
            }
        }
        private global::System.Boolean _Approved;
        partial void OnApprovedChanging(global::System.Boolean value);
        partial void OnApprovedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte EID
        {
            get
            {
                return _EID;
            }
            set
            {
                OnEIDChanging(value);
                ReportPropertyChanging("EID");
                _EID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EID");
                OnEIDChanged();
            }
        }
        private global::System.Byte _EID;
        partial void OnEIDChanging(global::System.Byte value);
        partial void OnEIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte MID
        {
            get
            {
                return _MID;
            }
            set
            {
                OnMIDChanging(value);
                ReportPropertyChanging("MID");
                _MID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MID");
                OnMIDChanged();
            }
        }
        private global::System.Byte _MID;
        partial void OnMIDChanging(global::System.Byte value);
        partial void OnMIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK__TravelAdvan__EID__15502E78", "Employee")]
        public Employee Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DatabaseModel.FK__TravelAdvan__EID__15502E78", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DatabaseModel.FK__TravelAdvan__EID__15502E78", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DatabaseModel.FK__TravelAdvan__EID__15502E78", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("DatabaseModel.FK__TravelAdvan__EID__15502E78", "Employee", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK__TravelAdvan__MID__164452B1", "Mission")]
        public Mission Mission
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mission>("DatabaseModel.FK__TravelAdvan__MID__164452B1", "Mission").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mission>("DatabaseModel.FK__TravelAdvan__MID__164452B1", "Mission").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Mission> MissionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mission>("DatabaseModel.FK__TravelAdvan__MID__164452B1", "Mission");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Mission>("DatabaseModel.FK__TravelAdvan__MID__164452B1", "Mission", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Trip")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Trip : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Trip object.
        /// </summary>
        /// <param name="eID">Initial value of the EID property.</param>
        /// <param name="mID">Initial value of the MID property.</param>
        /// <param name="cID">Initial value of the CID property.</param>
        /// <param name="startDate">Initial value of the StartDate property.</param>
        public static Trip CreateTrip(global::System.Byte eID, global::System.Byte mID, global::System.Byte cID, global::System.DateTime startDate)
        {
            Trip trip = new Trip();
            trip.EID = eID;
            trip.MID = mID;
            trip.CID = cID;
            trip.StartDate = startDate;
            return trip;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte EID
        {
            get
            {
                return _EID;
            }
            set
            {
                if (_EID != value)
                {
                    OnEIDChanging(value);
                    ReportPropertyChanging("EID");
                    _EID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EID");
                    OnEIDChanged();
                }
            }
        }
        private global::System.Byte _EID;
        partial void OnEIDChanging(global::System.Byte value);
        partial void OnEIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte MID
        {
            get
            {
                return _MID;
            }
            set
            {
                if (_MID != value)
                {
                    OnMIDChanging(value);
                    ReportPropertyChanging("MID");
                    _MID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MID");
                    OnMIDChanged();
                }
            }
        }
        private global::System.Byte _MID;
        partial void OnMIDChanging(global::System.Byte value);
        partial void OnMIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte CID
        {
            get
            {
                return _CID;
            }
            set
            {
                if (_CID != value)
                {
                    OnCIDChanging(value);
                    ReportPropertyChanging("CID");
                    _CID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CID");
                    OnCIDChanged();
                }
            }
        }
        private global::System.Byte _CID;
        partial void OnCIDChanging(global::System.Byte value);
        partial void OnCIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                if (_StartDate != value)
                {
                    OnStartDateChanging(value);
                    ReportPropertyChanging("StartDate");
                    _StartDate = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StartDate");
                    OnStartDateChanged();
                }
            }
        }
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StopDate
        {
            get
            {
                return _StopDate;
            }
            set
            {
                OnStopDateChanging(value);
                ReportPropertyChanging("StopDate");
                _StopDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StopDate");
                OnStopDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _StopDate;
        partial void OnStopDateChanging(Nullable<global::System.DateTime> value);
        partial void OnStopDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK__Trip__CID__1A14E395", "Country")]
        public Country Country
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Country>("DatabaseModel.FK__Trip__CID__1A14E395", "Country").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Country>("DatabaseModel.FK__Trip__CID__1A14E395", "Country").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Country> CountryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Country>("DatabaseModel.FK__Trip__CID__1A14E395", "Country");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Country>("DatabaseModel.FK__Trip__CID__1A14E395", "Country", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK__Trip__EID__182C9B23", "Employee")]
        public Employee Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DatabaseModel.FK__Trip__EID__182C9B23", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DatabaseModel.FK__Trip__EID__182C9B23", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("DatabaseModel.FK__Trip__EID__182C9B23", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("DatabaseModel.FK__Trip__EID__182C9B23", "Employee", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK__Trip__MID__1920BF5C", "Mission")]
        public Mission Mission
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mission>("DatabaseModel.FK__Trip__MID__1920BF5C", "Mission").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mission>("DatabaseModel.FK__Trip__MID__1920BF5C", "Mission").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Mission> MissionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mission>("DatabaseModel.FK__Trip__MID__1920BF5C", "Mission");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Mission>("DatabaseModel.FK__Trip__MID__1920BF5C", "Mission", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
